server:
  servlet:
    context-path: /mcs-indicadores/

spring:
  aop:
    proxy-target-class: true
    
logging:  
  config: /opt/data/mcs-minjus/log/mcs-indicadores/config/log4j2-mcs-indicadores.xml