
package pe.gob.minjus.indicadores.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecurityServiceWS", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecurityServiceWS {


    /**
     * 
     * @param rolId
     * @param ip
     * @param auditUser
     * @param cuentaId
     * @param aplicacionId
     * @param mac
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarAccesosPorCuenta", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RegistrarAccesosPorCuenta")
    @ResponseWrapper(localName = "registrarAccesosPorCuentaResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RegistrarAccesosPorCuentaResponse")
    public String registrarAccesosPorCuenta(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId,
        @WebParam(name = "rolId", targetNamespace = "")
        Integer rolId,
        @WebParam(name = "cuentaId", targetNamespace = "")
        Integer cuentaId,
        @WebParam(name = "ip", targetNamespace = "")
        String ip,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param auditUser
     * @param aplicacionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rolesPorAplicacion", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RolesPorAplicacion")
    @ResponseWrapper(localName = "rolesPorAplicacionResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RolesPorAplicacionResponse")
    public String rolesPorAplicacion(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId);

    /**
     * 
     * @param rolId
     * @param auditUser
     * @param aplicacionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cuentasPorRolId", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.CuentasPorRolId")
    @ResponseWrapper(localName = "cuentasPorRolIdResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.CuentasPorRolIdResponse")
    public String cuentasPorRolId(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId,
        @WebParam(name = "rolId", targetNamespace = "")
        Integer rolId);

    /**
     * 
     * @param auditUser
     * @param cuentaId
     * @param aplicacionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rolesPorCuenta", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RolesPorCuenta")
    @ResponseWrapper(localName = "rolesPorCuentaResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RolesPorCuentaResponse")
    public String rolesPorCuenta(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "cuentaId", targetNamespace = "")
        Integer cuentaId,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId);

    /**
     * 
     * @param newPasssword
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.ChangePasswordResponse")
    public String changePassword(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "newPasssword", targetNamespace = "")
        String newPasssword);

    /**
     * 
     * @param rolId
     * @param flagOnlyMenu
     * @param auditUser
     * @param aplicacionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "menusPorAplicacion", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.MenusPorAplicacion")
    @ResponseWrapper(localName = "menusPorAplicacionResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.MenusPorAplicacionResponse")
    public String menusPorAplicacion(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId,
        @WebParam(name = "rolId", targetNamespace = "")
        Integer rolId,
        @WebParam(name = "flagOnlyMenu", targetNamespace = "")
        Boolean flagOnlyMenu);

    /**
     * 
     * @param pass
     * @param ip
     * @param flagRegistrarAcceso
     * @param aplicacionId
     * @param user
     * @param mac
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.LoginResponse")
    public String login(
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "ip", targetNamespace = "")
        String ip,
        @WebParam(name = "mac", targetNamespace = "")
        String mac,
        @WebParam(name = "flagRegistrarAcceso", targetNamespace = "")
        Boolean flagRegistrarAcceso);

    /**
     * 
     * @param servicioId
     * @param user
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateIpByService", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.ValidateIpByService")
    @ResponseWrapper(localName = "validateIpByServiceResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.ValidateIpByServiceResponse")
    public boolean validateIpByService(
        @WebParam(name = "servicioId", targetNamespace = "")
        Integer servicioId,
        @WebParam(name = "user", targetNamespace = "")
        String user)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autenticar", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.Autenticar")
    @ResponseWrapper(localName = "autenticarResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.AutenticarResponse")
    public String autenticar(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param auditUser
     * @param usuario
     * @param aplicacionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rolesPorUsuario", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RolesPorUsuario")
    @ResponseWrapper(localName = "rolesPorUsuarioResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RolesPorUsuarioResponse")
    public String rolesPorUsuario(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId);

    /**
     * 
     * @param rolId
     * @param auditUser
     * @param objetoPadreId
     * @param aplicacionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "permisosPorMenu", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.PermisosPorMenu")
    @ResponseWrapper(localName = "permisosPorMenuResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.PermisosPorMenuResponse")
    public String permisosPorMenu(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId,
        @WebParam(name = "rolId", targetNamespace = "")
        Integer rolId,
        @WebParam(name = "objetoPadreId", targetNamespace = "")
        Integer objetoPadreId);

    /**
     * 
     * @param auditUser
     * @param aplicacionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cuentasPorAplicacion", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.CuentasPorAplicacion")
    @ResponseWrapper(localName = "cuentasPorAplicacionResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.CuentasPorAplicacionResponse")
    public String cuentasPorAplicacion(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ipClient", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.IpClient")
    @ResponseWrapper(localName = "ipClientResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.IpClientResponse")
    public String ipClient();

    /**
     * 
     * @param rolId
     * @param ip
     * @param auditUser
     * @param aplicacionId
     * @param user
     * @param mac
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarAccesosPorUsuario", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RegistrarAccesosPorUsuario")
    @ResponseWrapper(localName = "registrarAccesosPorUsuarioResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RegistrarAccesosPorUsuarioResponse")
    public String registrarAccesosPorUsuario(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId,
        @WebParam(name = "rolId", targetNamespace = "")
        Integer rolId,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "ip", targetNamespace = "")
        String ip,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param auditUser
     * @param aplicacionId
     * @param rolNombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cuentasPorRolNombre", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.CuentasPorRolNombre")
    @ResponseWrapper(localName = "cuentasPorRolNombreResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.CuentasPorRolNombreResponse")
    public String cuentasPorRolNombre(
        @WebParam(name = "auditUser", targetNamespace = "")
        String auditUser,
        @WebParam(name = "aplicacionId", targetNamespace = "")
        Integer aplicacionId,
        @WebParam(name = "rolNombre", targetNamespace = "")
        String rolNombre);

    /**
     * 
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateIp", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.ValidateIp")
    @ResponseWrapper(localName = "validateIpResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.ValidateIpResponse")
    public boolean validateIp()
        throws Exception_Exception
    ;

    /**
     * 
     * @param urlRecovery
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recoveryPassword", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RecoveryPassword")
    @ResponseWrapper(localName = "recoveryPasswordResponse", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", className = "pe.gob.minjus.indicadores.wsdl.RecoveryPasswordResponse")
    public String recoveryPassword(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "urlRecovery", targetNamespace = "")
        String urlRecovery);

}
