
package pe.gob.minjus.indicadores.wsdl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * http://desarrollo2.minjus.gob.pe/sgsi-security-ws/SecurityServiceWS?wsdl
 */
//@WebServiceClient(name = "SecurityServiceWS", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", wsdlLocation = "${url.ws.seguridad}")
@WebServiceClient(name = "SecurityServiceWS", targetNamespace = "http://service.ws.security.sgsi.minjus.gob.pe/", wsdlLocation = "http://desarrollo2.minjus.gob.pe/sgsi-security-ws/SecurityServiceWS?wsdl")
public class SecurityServiceWS_Service
    extends Service
{

    private final static URL SECURITYSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException SECURITYSERVICEWS_EXCEPTION;
    private final static QName SECURITYSERVICEWS_QNAME = new QName("http://service.ws.security.sgsi.minjus.gob.pe/", "SecurityServiceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/Users/Work-PC/eclipse-workspace/mcs-example/target/classes/SecurityServiceWS.wsdl");
            url = new URL("http://desarrollo2.minjus.gob.pe/sgsi-security-ws/SecurityServiceWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECURITYSERVICEWS_WSDL_LOCATION = url;
        SECURITYSERVICEWS_EXCEPTION = e;
    }

    public SecurityServiceWS_Service() {
        super(__getWsdlLocation(), SECURITYSERVICEWS_QNAME);
    }

    public SecurityServiceWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECURITYSERVICEWS_QNAME, features);
    }

    public SecurityServiceWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SECURITYSERVICEWS_QNAME);
    }

    public SecurityServiceWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECURITYSERVICEWS_QNAME, features);
    }

    public SecurityServiceWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityServiceWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecurityServiceWS
     */
    @WebEndpoint(name = "SecurityServiceWSPort")
    public SecurityServiceWS getSecurityServiceWSPort() {
        return super.getPort(new QName("http://service.ws.security.sgsi.minjus.gob.pe/", "SecurityServiceWSPort"), SecurityServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecurityServiceWS
     */
    @WebEndpoint(name = "SecurityServiceWSPort")
    public SecurityServiceWS getSecurityServiceWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.security.sgsi.minjus.gob.pe/", "SecurityServiceWSPort"), SecurityServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECURITYSERVICEWS_EXCEPTION!= null) {
            throw SECURITYSERVICEWS_EXCEPTION;
        }
        return SECURITYSERVICEWS_WSDL_LOCATION;
    }

}
